### ISSUE TITLE
last println not rebeing recieved..

### ISSUE THREAD

**Issue by kmb36td** [asjdf/WebSerialLite#4] opened 2022-12-08 10:42 UTC
```
WebSerial.println(" ");
    WebSerial.println("List of Available Commands:");
    WebSerial.println("");
    WebSerial.println("help \"print help\"");
    WebSerial.println("geteeprom \"Print EEPROM settings.\"");
    WebSerial.println("setcur<space><decimal 20.0-100.0> \"Set motor current setting.\"");
    WebSerial.println("setaccel<space><decimal 0.04-1.0> \"Set accel setting.\"");
    WebSerial.println("setangle<space><decimal 0.0-360.0> \"Set turn Angle setting.\"");
    WebSerial.println("streamdata<space><\"true\" or \"false\"> \"Print streamdata.\"");
```
abaove code prints.. but the last printline not being recieved "streamdata" not printed..
```
 
List of Available Commands:

help "print help"
geteeprom "Print EEPROM settings."
setcur<space><decimal 20.0-100.0> "Set motor current setting."
setaccel<space><decimal 0.04-1.0> "Set accel setting."
setangle<space><decimal 0.0-360.0> "Set turn Angle setting."
```

**Comment by asjdf** [comment] 2022-12-08 12:59
Thanks for your report.

I found that the problem you encountered may not be caused by this library, but by ESPAsyncWebServer (I think this is a feature of the library, although there are some things that can be improved). As you can see in https://github.com/me-no-dev/ESPAsyncWebServer/blob/f71e3d427b5be9791a8a2c93cf8079792c3a9a26/src/AsyncWebSocket.cpp#L550 , they limit the length of queue, and they define the max length of queue to 8 for ESP8266, you can check in https://github.com/me-no-dev/ESPAsyncWebServer/blob/f71e3d427b5be9791a8a2c93cf8079792c3a9a26/src/AsyncWebSocket.h#L30.

So if you want to send many messages  through websocket rapidly, I recommand you make a temp storage. Or you can edit the ESPAsyncWebServer to solve this problem. By the way, I create a PR try to let user config the WS_MAX_QUEUED_MESSAGES (https://github.com/esphome/ESPAsyncWebServer/pull/10), hope it can be proved.XD

**Comment by asjdf** [comment] 2022-12-17 15:30
If your problem is solved, you can close this issue.
Or do you still have questions?

**Comment by Bromiun** [comment] 2023-01-19 11:14
I am having the same problem, and it makes WebserLite quite unusable.  I have the same problem with Webser non-lite, which points to the issue that you raised -- it being a problem with async websocket.

I will check your recommendation above, and if it does not fix the problem, I will be back.

Also, how do I make the window larger both horizontally and vertically.  How can I do:
"you should install NodeJS and pnpm first." ?  I am using Arduino IDE on Windows.  I also have access to VSCode.

Thanks!

**Comment by asjdf** [comment] 2023-01-22 04:52
> Also, how do I make the window larger both horizontally and vertically. How can I do: "you should install NodeJS and pnpm first." ? I am using Arduino IDE on Windows. I also have access to VSCode.

You can find that I put `finalize.mjs` under the frontend folder. This is a small tool I made for automated code generation. It is written in js, so you need a package manager ( I recommend `pnpm`) and an environment that can run js.
If you don't know much about front-end knowledge or want to simplify the installation process, you can try to use `scoop` to help you install `NodeJS` and `pnpm` (scoop is a software manager under windows).

If you have any questions please feel free to ask and if this library helps you please give it a star, thank you😀.

**Closed** 2023-03-21 05:52 UTC
