### ISSUE TITLE
Issue with the Terminal

### ISSUE THREAD

**Issue by Bromiun** [asjdf/WebSerialLite#8] opened 2023-01-23 18:50 UTC
Hi Atom - Issue #4 did not show up, although I got several errors on the serial monitor that
"ERROR: Too many messages queued".  However, it did not appear data was dropped.

Another issue. Terminal is too slow.

Where does console.log() output go?

Is there a JS function to put the data on the browser screen, instead of the Terminal?  
Even better, is there a way to direct WebSocket output to the browser screen rather than to JS?

Thanks
Bromium

**Comment by asjdf** [comment] 2023-01-26 01:11
"Terminal is too slow" I think it should be caused by the long-time-cost function in the loop function. If I recall correctly, the web service library handles the request from the client every time it completes a loop.

console.log() put messages into your browser's developer tool (F12 -> control)
![image](https://user-images.githubusercontent.com/22193008/214730830-7a1dd49b-642d-4886-8171-6c5b3b7a1a58.png)

And I'm a bit confused about what "browser screen" and "Terminal" mean respectively.
WebSocket is a communication protocol, so it is impossible to directly display its communication content on a web page without using JS.

If you want to adjust the front-end style, it is actually not difficult, mainly to adjust the css. But if you want to optimize the response speed, then obviously the focus is not on the front end, but on the microcontroller. Because if you haven’t even encountered the limitation of the MCU library, then the problem will definitely not lie in the browser or JS (obviously, the performance of mobile phones/computers is much higher than that of MCUs)

**Comment by Bromiun** [comment] 2023-01-26 05:01
Yes, I need to display the communication content (which is event.data) on the web page.

What is the JS function that would do that?  Would it be something like the JS function WebPrint(event.data)?

This is the last piece of my puzzle.  Your help is GREATLY appreciated!

Bromium

**Comment by asjdf** [comment] 2023-01-26 13:00
https://github.com/asjdf/WebSerialLite/blob/4fbab34726a0dbbc677baa5167ac8fa7ea508306/frontend/index.html#L221
This line is used to get the web page element that store communication content (looks like a terminal).

https://github.com/asjdf/WebSerialLite/blob/4fbab34726a0dbbc677baa5167ac8fa7ea508306/frontend/index.html#L281
The function `terminalWrite` is used to write the raw messages into the element `textArea` that matched in line 221.

Glad to be able to help you, you are very kind😀.

**Comment by Bromiun** [comment] 2023-02-05 00:11
Hi Atom -- my apologies for this delayed reply.  More later.

I have decided to go the way of a terminal, for serial monitoring.  

So I now have 3 servers (which is just too many). 1- Web server on port 80 using WiFiServer.  2- Update server on port 89 using WebServer, and 3- Terminal server on port 88 using WifiServer.  

On the PC I am using Putty the terminal emulator.  It works great and fast.  I tried this a while ago and it failed.  The problem is that Putty must be set in "RAW" mode, or it will fail to work properly.

Now the problem is that I have too many servers.  Is there any way to do OTA update on WifiServer so I can eliminate server #2?

Is there any way to eliminate server #3 by allowing WiFiServer to have 2 clients?  It appears to take only one client.

Thanks -- Bromium

**Comment by asjdf** [comment] 2023-02-05 06:55
Hi Bromium, glad to hear from you.

First of all, ESPAsyncWebServer is actually a great alternative to WiFiServer (non-blocking will undoubtedly help you a lot with your project.) ), so I recommend using ESPAsyncWebServer instead of WiFi Server (it shouldn't be too complicated and will reduce the size of the firmware).

Also, I don't quite understand why a server would be set up on three different ports. Is there a special purpose? WebSerialLite initialization simply registers two routes on the server to provide services, so you should only need to create a server and register your routes.
For example:
https://github.com/asjdf/WebSerialLite/blob/4fbab34726a0dbbc677baa5167ac8fa7ea508306/examples/demo/demo.ino#L47

In addition, I saw that you mentioned the need for OTA, in fact, WebServer can also implement OTA.

I'm sorry that because of the language problem, I may not be able to understand your needs very well, feel free to ask. 😊

**Comment by asjdf** [comment] 2023-03-21 05:53
Since this issue has not been updated for a long time, I will close it. If you have any questions, please reopen this issue or open a new issue.

**Closed by asjdf** 2023-03-21 05:53 UTC
